-- DROP USER SSR_PROJECT;

CREATE USER SSR_PROJECT
-- IDENTIFIED BY <password>
;

CREATE TABLE "SSR_PROJECT"."BOOK" 
   (	"BOOK_ID" NUMBER, 
	"BOOK_IMG" VARCHAR2(1000), 
	"BOOK_TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"BOOK_WRITER" VARCHAR2(50) NOT NULL ENABLE, 
	"BOOK_COMPANY" VARCHAR2(200) NOT NULL ENABLE, 
	"BOOK_GENRE" VARCHAR2(40) NOT NULL ENABLE, 
	"BOOK_YEAR" DATE, 
	"BOOK_ISBN" VARCHAR2(200) NOT NULL ENABLE, 
	"BOOK_PAGES" NUMBER NOT NULL ENABLE, 
	"BOOK_STORY" VARCHAR2(1000), 
	"BOOK_RATING" NUMBER(2,1) DEFAULT 0.0, 
	"BOOK_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"BOOK_UPDATED_AT" DATE, 
	 PRIMARY KEY ("BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("BOOK_TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("BOOK_ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SSR_PROJECT"."LIBRARY" 
   (	"LIBRARY_ID" NUMBER, 
	"LIBRARY_CODE" NUMBER NOT NULL ENABLE, 
	"LIBRARY_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"LIBRARY_ADDR" VARCHAR2(200) NOT NULL ENABLE, 
	"LIBRARY_LAT" NUMBER(10,7) NOT NULL ENABLE, 
	"LIBRARY_LON" NUMBER(11,7) NOT NULL ENABLE, 
	"LIBRARY_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LIBRARY_UPDATED_AT" DATE, 
	 PRIMARY KEY ("LIBRARY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("LIBRARY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("LIBRARY_ADDR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SSR_PROJECT"."MEMBERS" 
   (	"MEMBER_ID" NUMBER, 
	"MEMBER_PASSWORD" VARCHAR2(255) NOT NULL ENABLE, 
	"MEMBER_NICKNAME" VARCHAR2(20) NOT NULL ENABLE, 
	"MEMBER_EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"MEMBER_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"MEMBER_BIRTH" DATE NOT NULL ENABLE, 
	"MEMBER_RULE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_IMGURL" VARCHAR2(1000), 
	"MEMBER_ADDR" VARCHAR2(200), 
	"MEMBER_INTRO" VARCHAR2(300), 
	"MEMBER_STATE" VARCHAR2(20), 
	"MEMBER_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MEMBER_UPDATED_AT" DATE, 
	 CHECK (MEMBER_STATE IN ('활동', '정지', '휴먼')) ENABLE, 
	 PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("MEMBER_NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("MEMBER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "SSR_PROJECT"."READ_BOOK" 
   (	"MEMBER_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"READ_BOOK_STATE" VARCHAR2(20) DEFAULT '읽는 중' NOT NULL ENABLE, 
	"READ_BOOK_START" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"READ_BOOK_END" DATE, 
	"READ_BOOK_MEMO" VARCHAR2(2000), 
	"READ_BOOK_RATING" NUMBER(2,1) DEFAULT 0.0 NOT NULL ENABLE, 
	"READ_BOOK_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"READ_BOOK_UPDATED_AT" DATE, 
	 CHECK (READ_BOOK_STATE IN ('읽는 중', '완독')) ENABLE, 
	 CONSTRAINT "PK_READ_BOOK" PRIMARY KEY ("MEMBER_ID", "BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SSR_PROJECT"."READ_BOOK" ADD CONSTRAINT "FK_READ_BOOK_BOOK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SSR_PROJECT"."BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SSR_PROJECT"."READ_BOOK" ADD CONSTRAINT "FK_READ_BOOK_MEMBERS" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSR_PROJECT"."MEMBERS" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
;

CREATE TABLE "SSR_PROJECT"."READ_SOON" 
   (	"MEMBER_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"READ_SOON_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"READ_SOON_UPDATED_AT" DATE, 
	 CONSTRAINT "PK_READ_SOON" PRIMARY KEY ("MEMBER_ID", "BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SSR_PROJECT"."READ_SOON" ADD CONSTRAINT "FK_READ_SOON_BOOK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SSR_PROJECT"."BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SSR_PROJECT"."READ_SOON" ADD CONSTRAINT "FK_READ_SOON_MEMBERS" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSR_PROJECT"."MEMBERS" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
;

CREATE TABLE "SSR_PROJECT"."REVIEW" 
   (	"REVIEW_ID" NUMBER, 
	"BOOK_ID" NUMBER NOT NULL ENABLE, 
	"MEMBER_ID" NUMBER NOT NULL ENABLE, 
	"REVIEW_COMMENT" VARCHAR2(200), 
	"REVIEW_RATING" NUMBER(2,1) DEFAULT 0.0, 
	"REVIEW_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"REVIEW_UPDATED_AT" DATE, 
	 PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_BOOK_MEMBER" UNIQUE ("BOOK_ID", "MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SSR_PROJECT"."REVIEW" ADD CONSTRAINT "FK_BOOK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SSR_PROJECT"."BOOK" ("BOOK_ID") ENABLE;
  ALTER TABLE "SSR_PROJECT"."REVIEW" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSR_PROJECT"."MEMBERS" ("MEMBER_ID") ENABLE;
;

CREATE TABLE "SSR_PROJECT"."REVIEW_LIKES" 
   (	"MEMBER_ID" NUMBER, 
	"REVIEW_ID" NUMBER, 
	"REVIEW_LIKES_CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"REVIEW_LIKES_UPDATED_AT" DATE, 
	 CONSTRAINT "PK_REVIEW_LIKES" PRIMARY KEY ("MEMBER_ID", "REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "SSR_PROJECT"."REVIEW_LIKES" ADD CONSTRAINT "FK_LIKES_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSR_PROJECT"."MEMBERS" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SSR_PROJECT"."REVIEW_LIKES" ADD CONSTRAINT "FK_LIKES_REVIEW" FOREIGN KEY ("REVIEW_ID")
	  REFERENCES "SSR_PROJECT"."REVIEW" ("REVIEW_ID") ON DELETE CASCADE ENABLE;
;

CREATE SEQUENCE SSR_PROJECT.BOOK_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE SSR_PROJECT.LIBRARY_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE SSR_PROJECT.MEMBER_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE SSR_PROJECT.REVIEW_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE SSR_PROJECT.BOOK_HOLDING_CACHE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE SSR_PROJECT.BOOK_LOAN_CACHE_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE TABLE "SSR_PROJECT"."BOOK_LOAN_CACHE"
   (	"CACHE_ID" NUMBER,
	"BOOK_ISBN" VARCHAR2(20) NOT NULL ENABLE,
	"LIBRARY_CODE" NUMBER NOT NULL ENABLE,
	"LOAN_AVAILABLE" CHAR(1),
	"CACHED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 PRIMARY KEY ("CACHE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SYSTEM"  ENABLE,
	 UNIQUE ("BOOK_ISBN", "LIBRARY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;

CREATE TABLE "SSR_PROJECT"."BOOK_HOLDING_CACHE"
   (	"CACHE_ID" NUMBER,
	"BOOK_ISBN" VARCHAR2(20) NOT NULL ENABLE,
	"REGION_CODE" NUMBER(5) NOT NULL ENABLE,
	"DTL_REGION" NUMBER(10) DEFAULT 0 NOT NULL ENABLE,
	"LIBRARY_CODES" VARCHAR2(4000),
	"CACHED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 PRIMARY KEY ("CACHE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SYSTEM"  ENABLE,
	 UNIQUE ("BOOK_ISBN", "REGION_CODE", "DTL_REGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;