CREATE TABLE MEMBERS (
   MEMBER_ID          NUMBER        PRIMARY KEY,
   MEMBER_PASSWORD    VARCHAR2(255)  NOT NULL,
   MEMBER_NICKNAME    VARCHAR2(20)  NOT NULL UNIQUE,
	 MEMBER_EMAIL       VARCHAR2(100) NOT NULL UNIQUE,
   MEMBER_NAME        VARCHAR2(50)  NOT NULL,
   MEMBER_BIRTH       DATE          NOT NULL,
   MEMBER_RULE        VARCHAR2(1)   DEFAULT 'N' NOT NULL,
   MEMBER_IMGURL      VARCHAR2(1000),
   MEMBER_ADDR        VARCHAR2(200),
   MEMBER_INTRO       VARCHAR2(300),
   MEMBER_STATE       VARCHAR2(3)   CHECK (MEMBER_STATE IN ('활동', '정지', '휴먼')),
   MEMBER_CREATED_AT  DATE          DEFAULT SYSDATE NOT NULL,
   MEMBER_UPDATED_AT  DATE         
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE BOOK_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE TABLE BOOK (
  BOOK_ID         NUMBER PRIMARY KEY,
  BOOK_IMG        VARCHAR2(1000),
  BOOK_TITLE      VARCHAR2(100) NOT NULL UNIQUE,
  BOOK_WRITER     VARCHAR2(50) NOT NULL,
  BOOK_COMPANY    VARCHAR2(200) NOT NULL,
  BOOK_GENRE      VARCHAR2(40) NOT NULL CHECK(BOOK_GENRE IN ('소설', '에세이', '경제/경영', '자기계발', '역사', '과학', '인문', '시/시집', '기타')),
  BOOK_YEAR       DATE,
  BOOK_ISBN       VARCHAR2(200) NOT NULL UNIQUE,
  BOOK_PAGES      NUMBER NOT NULL,
  BOOK_STORY      VARCHAR2(1000),
  BOOK_RATING     NUMBER(2, 1) DEFAULT 0.0,
  BOOK_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  BOOK_UPDATED_AT DATE
);

CREATE TABLE LIBRARY(
	LIBRARY_ID NUMBER PRIMARY KEY,
	LIBRARY_CODE NUMBER NOT NULL UNIQUE,
	LIBRARY_NAME VARCHAR2(200) NOT NULL ,
	LIBRARY_ADDR VARCHAR2(200) NOT NULL UNIQUE,
	LIBRARY_LAT NUMBER(10, 7) NOT NULL,
	LIBRARY_LON NUMBER(11, 7) NOT NULL,
	LIBRARY_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
	LIBRARY_UPDATED_AT DATE
);

CREATE SEQUENCE LIBRARY_SEQ
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOCYCLE;
	
CREATE TABLE READ_SOON (
  MEMBER_ID NUMBER,
  BOOK_ID   NUMBER,
  READ_SOON_CREATED_AT  DATE  DEFAULT SYSDATE NOT NULL,
  READ_SOON_UPDATED_AT  DATE,
  CONSTRAINT pk_READ_SOON         PRIMARY KEY (MEMBER_ID, BOOK_ID),
  CONSTRAINT fk_READ_SOON_MEMBERS FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
  CONSTRAINT fk_READ_SOON_BOOK    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK(BOOK_ID)      ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    REVIEW_ID         NUMBER PRIMARY KEY,
    BOOK_ID           NUMBER NOT NULL,
    MEMBER_ID         NUMBER NOT NULL,
    REVIEW_COMMENT    VARCHAR2(200),
    REVIEW_RATING     NUMBER(2,1) DEFAULT 0.0,
    REVIEW_CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    REVIEW_UPDATED_AT DATE,
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
    CONSTRAINT UK_BOOK_MEMBER UNIQUE (BOOK_ID, MEMBER_ID)
);

CREATE SEQUENCE REVIEW_SEQ
       START WITH 1
       INCREMENT BY 1
       NOCACHE
       NOCYCLE;

CREATE TABLE REVIEW_LIKES(
  MEMBER_ID NUMBER,
  REVIEW_ID NUMBER,
  REVIEW_LIKES_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  REVIEW_LIKES_UPDATED_AT DATE,
  CONSTRAINT PK_REVIEW_LIKES PRIMARY KEY (MEMBER_ID, REVIEW_ID),
  CONSTRAINT FK_LIKES_MEMBER FOREIGN KEY (MEMBER_ID) 
      REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_LIKES_REVIEW FOREIGN KEY (REVIEW_ID) 
      REFERENCES REVIEW(REVIEW_ID) ON DELETE CASCADE
);

CREATE TABLE READ_BOOK (
  MEMBER_ID             NUMBER,
  BOOK_ID               NUMBER,
  READ_BOOK_STATE       VARCHAR2(20) DEFAULT '읽는 중' NOT NULL   CHECK (READ_BOOK_STATE IN ('읽는 중', '완독')),
  READ_BOOK_START       DATE            DEFAULT SYSDATE NOT NULL,
  READ_BOOK_END         DATE,
  READ_BOOK_MEMO        VARCHAR2(2000),
  READ_BOOK_RATING      NUMBER(2, 1)    DEFAULT 0.0     NOT NULL,
  READ_BOOK_CREATED_AT  DATE            DEFAULT SYSDATE NOT NULL,
  READ_BOOK_UPDATED_AT  DATE,
  CONSTRAINT pk_READ_BOOK         PRIMARY KEY (MEMBER_ID, BOOK_ID),
  CONSTRAINT fk_READ_BOOK_MEMBERS  FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
  CONSTRAINT fk_READ_BOOK_BOOK    FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE
);