spring.application.name=library

# OracleDB connection settings
server.port=8111
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=ssr_project
spring.datasource.password=ssrpro

# Kakao Map
kakao.map.key=${KAKAO_MAP_JS_KEY}

# Public APIs
api.book.key=${PUBLIC_BOOK_API_KEY}
api.library.key=${LIBRARY_API_KEY}

# Firebase
firebase.config.path=${FIREBASE_CONFIG_PATH}
firebase.storage.bucket=${FIREBASE_STORAGE_BUCKET}