-- 정보나루 libSrchByBook 응답 캐시 (일 500건 API 한도 대응)
-- SSR_PROJECT 스키마에서 실행

CREATE SEQUENCE BOOK_HOLDING_CACHE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE BOOK_HOLDING_CACHE (
    CACHE_ID       NUMBER NOT NULL,
    BOOK_ISBN      VARCHAR2(20) NOT NULL,
    REGION_CODE    NUMBER(5) NOT NULL,
    DTL_REGION     NUMBER(10) DEFAULT 0 NOT NULL,
    LIBRARY_CODES  VARCHAR2(4000),
    CACHED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOOK_HOLDING_CACHE PRIMARY KEY (CACHE_ID),
    CONSTRAINT UQ_BOOK_HOLDING_CACHE UNIQUE (BOOK_ISBN, REGION_CODE, DTL_REGION)
);

-- UNIQUE (BOOK_ISBN, REGION_CODE, DTL_REGION) 제약이 동일 컬럼 인덱스를 이미 만듦 → 별도 INDEX 불필요 (ORA-01408 방지)
