-- 정보나루 bookExist(대출 가능 여부) 응답 캐시
-- Oracle 접속 계정(ssr_project 등)으로 1회 실행. 테이블 없으면 상세 페이지 SQL 오류 발생.
CREATE SEQUENCE BOOK_LOAN_CACHE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE BOOK_LOAN_CACHE (
    CACHE_ID        NUMBER NOT NULL,
    BOOK_ISBN       VARCHAR2(20) NOT NULL,
    LIBRARY_CODE    NUMBER NOT NULL,
    LOAN_AVAILABLE  CHAR(1),
    CACHED_AT       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BOOK_LOAN_CACHE PRIMARY KEY (CACHE_ID),
    CONSTRAINT UQ_BOOK_LOAN_CACHE UNIQUE (BOOK_ISBN, LIBRARY_CODE)
);
